// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID                  int32            `json:"id"`
	CreatorID           pgtype.Int4      `json:"creator_id"`
	VenueID             pgtype.Int4      `json:"venue_id"`
	Name                string           `json:"name"`
	Description         pgtype.Text      `json:"description"`
	StartTime           pgtype.Timestamp `json:"start_time"`
	EndTime             pgtype.Timestamp `json:"end_time"`
	Location            string           `json:"location"`
	MaxParticipants     int32            `json:"max_participants"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	CurrentParticipants pgtype.Int4      `json:"current_participants"`
}

type EventAttendee struct {
	ID        int32            `json:"id"`
	EventID   int32            `json:"event_id"`
	UserID    int32            `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Status    pgtype.Text      `json:"status"`
}

type User struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Venue struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Address     string `json:"address"`
	MaxCapacity int32  `json:"max_capacity"`
}
